version: "3.8"

services:
 app:
  container_name: app
  restart: always
  build: .
  ports:
   - "9090:9090"
  links:
   - mongo
 mongo:
  container_name: mongo
  image: mongo
  ports:
   - '27017:27017'
